inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - node_modules/**/*
    - db/schema.rb
    - db/migrate/**

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/BlockLength:
  Exclude:
    - 'spec/**/*'
    - Guardfile

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/StringLiterals:
  Exclude:
    - 'bin/*'
