AllCops:
  Exclude:
    - node_modules/**/*
    - db/schema.rb
    - db/migrate/**

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/BlockLength:
  Exclude:
    - 'spec/**/*'
    - Guardfile

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/StringLiterals:
  Exclude:
    - 'bin/*'
  
Style/MutableConstant:
  Exclude:
    - 'bin/webpack-dev-server'

# 112 is the longest line in rails generated files
Metrics/LineLength:
  Max: 112
  Exclude:
    - config/initializers/devise.rb
    - 'bin/webpack-dev-server'
