inherit_from: .rubocop_todo.yml

AllCops:
  Excludes:
    - node_modules/**/*

# Offense count: 5
Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'app/controllers/*'
    - 'app/helpers/application_helper.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/application_record.rb'
    - 'config/application.rb'
